common: &common
  weibo:
    api_key: "1882389022"
    api_secret: "1dcf2faeabab6b566ac2e624c20d8743"
    redirect_uri: "http://112.124.47.39/users/auth/weibo/callback"

  qq_connect:
    api_key: "801438532"
    api_secret: "b13d1d1e92e13ca52fc0de328edbb959"
    redirect_uri: "http://112.124.47.39/users/auth/qq_connect/callback"

production:
  <<: *common

development:
  <<: *common

test:
  <<: *common